### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by Megasu** [iiunknown/iscroll5.doc.cn#4]
既然都翻译好了，建议弄一个线上的链接，能帮助更多又需要的人。

标题名是个链接格式的，习惯性会复制iscroll5.doc.cn 查看有没有线上的文档，结果打开是个广告，这个不太友好。

文档的链接应该是这个吧，建议在进来第一个Readme加个链接。
<a href="http://iiunknown.gitbooks.io/iscroll-5-api-cn/content/" target=“_blank”>http://iiunknown.gitbooks.io/iscroll-5-api-cn/content/</a>

**Comment by iiunknown** [comment]
好的，谢谢。

**Comment by iiunknown** [comment]
已经添加
